#cloud-config
packages:
  - jq

write_files:
  - path: /etc/vault.d/vault.conf
    content: ${vault_conf}
    permissions: '0644'
    owner: vault:vault
    encoding: b64
  - path: /etc/environment
    content: |
      VAULT_ADDR=http://${ip_address}:8200
    append: true
  - path: /etc/vault.d/license.hclic
    content: |
      ${vault_license}
    owner: vault:vault
    permissions: '0600'
runcmd:
  - systemctl enable vault 
  - systemctl start vault && date && sleep 15
  - date && vault operator init --format=json -address http://${ip_address}:8200 > /tmp/vault_init
  - 'jq ''{"text": .root_token}'' /tmp/vault_init > /tmp/root_token'
  - 'curl -H "Content-type: application/json" -d "@/tmp/root_token" ${slack_webhook}'