#cloud-config
packages:
  - jq

write_files:
  - path: /etc/vault.d/vault.conf
    content: ${vault_conf}
    permissions: '0644'
    owner: vault:vault
    encoding: b64
  - path: /etc/environment
    content: |
      VAULT_ADDR=http://${ip_address}:8200
    append: true
  - path: /etc/vault.d/license.txt
    content: ${vault_license}

runcmd:
  - systemctl enable vault 
  - systemctl start vault && sleep 15
  - 'sleep 60 && vault operator init --format=json > /tmp/vault_init'
  - 'jq ''{"test": .root_token}'' /tmp/vault_init > /tmp/root_token'
  - 'curl -X POST -H ''Content-type: application/json'' -- data $(cat /tmp/root_token) ${slack_webhook}'